name=GPStar Audio Serial
version=1.0.2
author=GPStar Technologies
license=GPL-3.0-or-later
maintainer=GPStar Technologies <contact@gpstartechnologies.com>
sentence=Control your GPStar Audio boards with serial communication commands.
paragraph=A serial communication control library for the GPStar Audio and GPStar Audio XL series of audio boards from GPStar Technologies.
category=Device Control
architectures=*
url=https://github.com/GPStarTechnologies/GPStarAudio-Serial
includes=GPStarAudio.h
