name: Publish PlatformIO Library

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to PlatformIO
        uses: bojit/platformio-publish@main
        with:
          token: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
